# Generated by Django 5.0 on 2023-12-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceline',
            old_name='produit',
            new_name='product',
        ),
    ]
